#  Copyright 2024-2025 Dataport. All rights reserved. Developed as part of the POSSIBLE project.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

---
apiVersion: v1
kind: Service
metadata:
  name: participant-portal-backend-svc
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: portal-backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: participant-portal-backend
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: portal-backend
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: portal-backend
    spec:
      imagePullSecrets:
        - name: github-registry-auth
      containers:
        - name: backend-springboot
          env:
            - name: SERVER_SERVLET_CONTEXT_PATH
              value: /api
          envFrom:
            #- configMapRef:
            #    name: database
            - configMapRef:
                name: participant-portal-config
            - secretRef:
                name: fh-secret
          #image: ghcr.io/possible-x/backend:e064cddf59d2a4b7a70f2dba8f599113bda1ac18
          image: backend-image
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            tcpSocket:
              port: 8080
            timeoutSeconds: 1
          ports:
            - containerPort: 8080
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 3
            successThreshold: 1
            tcpSocket:
              port: 8080
            timeoutSeconds: 1
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
