---
apiVersion: v1
kind: Service
metadata:
  name: backend-svc
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: portal-backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-backend
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: portal-backend
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: portal-backend
    spec:
      imagePullSecrets:
        - name: github-registry-auth
      containers:
        - name: backend-springboot
          env:
            - name: SERVER_SERVLET_CONTEXT_PATH
              value: /api
          envFrom:
            - configMapRef:
                name: database
            - configMapRef:
                name: portal-variables
#            - secretRef:
#                name: portal-database-secret
          #image: ghcr.io/possible-x/backend:e064cddf59d2a4b7a70f2dba8f599113bda1ac18
          image: backend-image
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            tcpSocket:
              port: 8080
            timeoutSeconds: 1
          ports:
            - containerPort: 8080
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 3
            successThreshold: 1
            tcpSocket:
              port: 8080
            timeoutSeconds: 1
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
