#  Copyright 2024-2025 Dataport. All rights reserved. Developed as part of the POSSIBLE project.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: fh-secret
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    FH_CATALOG_SECRETKEY: AgDaeqp3VQCe/mXhGuP5mYiCrYpbtxmO/8dHdmvcbGOFXJ2Xo8Ll7RGcrx+ySIu/Gz0GZdQ/5p2438NX/EwE1t+oUi4HL2w+a2Mm45FLQ4hYI7POleVo1n2n30guE4k5BpbBz0d3iBGrB00UWhUf6ZbKhG+JIr/BfRK9uFPQd2PvWyWm4NCOhLI/c/RpiZai+7JhQFU01uuasscFQCfTs1w9DUUmmz58C+mV67DRBayIu+bb99hjtODbp/PvrBMuW+WvnEOsOyaumh8REGfZU/nJkroIGAlTf1bZc4WIwzXTTs3jIN3ZSfShprDcSLARrhlNg22Mg8PwlHosqgoEFRQABaSXhQ391XLhOMPJT+cZ+K/zxyIIsqvB0Yzt4075cNVwsvyZnADttznNUCcC/ayyJhx3x/ZrPT5YRZgu0wqykRdpaOBsawrVXGuQfFqg+Xzoiv8ycCXh+ARxKYksluiUHDKzVL8HeONf+0m7yt6v6AOvNh28yxBVok/Uunp7l+flV41Rbq2550BYE2Xb0LG+LLsTDLYMEC2bc/oiO5BEkP0fgoaHgvpzvJ9ls1jf9WTdfBZR0foBYu58+V0PcZRtiTrlyLxyolW4p7juCmJaNgCiuGqsrJQSwSYFl3i4+ZCkaK29KS4T84glnk+d9C15mteOQkdFoBfhMe/X6+g7L0evoUXN52ZLM/M3APd0EDUU53TScQPb5OQiaUBKtrZJ8oeeMRIkxIZHpOAxbgFdl6lN5nSk9sITi+IW+EfyNw1uLpamvdhJQ9PQZUciNsRvwHE2a66TC0L4XKC0N9VYKNhzaf/OdlOJFHsK2wLIUzvmoQ/YYy95XeF9D0yHTTtGvCgirHTltk/8gyU=
    EDC_XAPIKEY: AgCY/D8ZA+fdWBBsiqLW0Np/zbwXk2DVFE+w3Oex4QtBcG7WTqjsKqom4jXj9UhSDHfb4Est9G9/gWb5jm+kfn8XiY5nimFd5pLhZk7vUONKM6628khQI2thadmyl3vgmDivOZRq9RMbGZTyg0/KasWHz7Sb1OxSS8Ypo19PCFfT7MieF5+/JwItXNmrqdCpleh213sef9hqNs+rruda921Ayk89+LUhq6B4+z4bwfgr7VhY0QWfZe7rEOivkelv0kT3zDzIp4AqcQfyoj9b+GpDW7Kxa1YWJ9m4BtLM0Bn2S9Oo8UgOeL5OPcGKJYOXmajudT6Qmc2XsrjKrY3d85B2zrEXlFMWMDcu9OxzQ1ROO/zfWAwyGED6OleNVhx/FW9Hmr3nZ+/jTZyRzNcd1+4fiIGIbef/wTpKKvKtRCtSsEjyg7MVVv0+2RzJ4tKFxfEDaoTiUFcs1rt5e8x1ZyMm88WmD7Vv3xWJVehvkoCE639cUz7+y42vhUZSVOFNb0kxFsRxcg1D9UxjMp1FfSI2Qa+3kxg9bmYvMxN/CWgojxNtGcK+IrDM+fJFcjK+ZG4WJBGjtjvHYoh382EqjLbcnQi3pU2zPNXLBT0MbEugAHryPQHAWBkdgsAs7/GfY5NOJ/Dm7tcbY3+0vdk4lae3qNUbTwCR0/9Y3xCEIHT5tUqVXvXBPmsIDr+pR1w2vudBLAoRlu+/yQ==