image:
  pullPolicy: Always
  tag: "latest-develop"

imagePullSecrets:
  - name: github-registry-auth

ingress:
  enabled: true
  hosts:
    - host: management.consumer.edc.dev.possible-x.de
      paths:
        - path: /
          portNumber: 80
          pathType: Prefix
  tls:
    - secretName: dev-consumer-edc-management-tls
      hosts:
        - management.consumer.edc.dev.possible-x.de

service:
  type: NodePort
  port: 80
  targetPort: 8080

application:
  variables:
    - name: consumer-management-variables
      data:
        SPRING_PROFILES_ACTIVE: dev
        FH_CATALOG_URL: https://catalog.dev.possible-x.de/
        EDC_MGMTBASEURL: https://consumer.edc.dev.possible-x.de/management
        EDC_PROTOCOLBASEURL: https://consumer.edc.dev.possible-x.de/protocol
        SDCREATIONWIZARDAPI_BASEURL: https://sd-creation-wizard.dev.possible-x.de
        S3_BUCKETSTORAGEREGION: eu-central-3 
        S3_BUCKETNAME: dev-consumer-edc-bucket-possible-31952746
        PARTICIPANTID: did:web:didwebservice.dev.possible-x.de:participant:a8d62eee-3a16-3a05-adc1-88404998d781
        DAPSSERVER_BASEURL: https://daps.dev.possible-x.de
  secrets:
    - consumer-management-secrets