image:
  pullPolicy: Always
  tag: "latest-develop"

imagePullSecrets:
  - name: github-registry-auth

ingress:
  enabled: true
  hosts:
    - host: management.provider.edc.dev.possible-x.de
      paths:
        - path: /
          portNumber: 80
          pathType: Prefix
  tls:
    - secretName: dev-provider-edc-management-tls
      hosts:
        - management.provider.edc.dev.possible-x.de

service:
  type: NodePort
  port: 80
  targetPort: 8080

application:
  variables:
    - name: provider-management-variables
      data:
        SPRING_PROFILES_ACTIVE: dev
        FH_CATALOG_URL: https://catalog.dev.possible-x.de/
        EDC_MGMTBASEURL: https://provider.edc.dev.possible-x.de/management
        EDC_PROTOCOLBASEURL: https://provider.edc.dev.possible-x.de/protocol
        SDCREATIONWIZARDAPI_BASEURL: https://sd-creation-wizard.dev.possible-x.de
        S3_BUCKETSTORAGEREGION: eu-central-3 
        S3_BUCKETNAME: dev-provider-edc-bucket-possible-31952746
        PARTICIPANTID: did:web:didwebservice.dev.possible-x.de:participant:901e847f-bded-32d5-8301-c0e2dfa8439f
        DAPSSERVER_BASEURL: https://daps.dev.possible-x.de/auth
  secrets:
    - provider-management-secrets