services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "${BACKEND_PORT:-8080}:8080"
    environment:
      - ACTIVEPROFILE=${ACTIVEPROFILE:-provider-local}

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT:-8081}:4200"
    environment:
      - ACTIVEPROFILE=${ACTIVEPROFILE:-provider-local}