#  Copyright 2024-2025 Dataport. All rights reserved. Developed as part of the POSSIBLE project.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

image:
  pullPolicy: Always
  tag: "latest-develop"

imagePullSecrets:
  - name: github-registry-auth

ingress:
  enabled: true
  hosts:
    - host: management.consumer.edc.poc.possible-x.de
      paths:
        - path: /
          portNumber: 80
          pathType: Prefix
  tls:
    - secretName: demo-consumer-edc-management-tls
      hosts:
        - management.consumer.edc.poc.possible-x.de

service:
  type: NodePort
  port: 80
  targetPort: 8080

application:
  variables:
    - name: consumer-management-variables
      data:
        SPRING_PROFILES_ACTIVE: dev
        FH_CATALOG_URL: https://possible.fokus.fraunhofer.de/api/hub/repo
        EDC_MGMTBASEURL: https://consumer.edc.poc.possible-x.de/management
        SDCREATIONWIZARDAPI_BASEURL: https://sd-creation-wizard.poc.possible-x.de
  secrets:
    - consumer-management-secrets