---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: management-secrets
  namespace: edc-dev-provider-management
spec:
  encryptedData:
    EDC_MGMTBASEURL: AgDIPzxvnpKgbHu7CzY3S7dwc4CCKMIA1ulkaiLYRxVNGHN6kyG0m1YMs+WHvV0k8Miq+lhCBqFQZSRz3DsLZSa/39VcFOCTUfo4H0ae6BC4mJaiWfZGqB4kmV7d2d+ll5bWd3kbEiqg8tux6bJegzrNPzLtLAqJn2HZh5m+w2K0z8YMelxfWPe2gmn03g7hbKuCdf/y3FwWSUCfNf8dyTHDzHTznwa+sVUzPblyV+DuQNVxaHYkHW1v8ccNZBXut46vv5DoIqEGhzUE/2nQiqr5rc+lIMkjRkzM4GyagZQ3pXYcny5KZ1+rrD1x+a13897pYgslNCPkflVjGAe7+v96bJ9/roY9oI9lqbusx9ULwyw/5abJ/wC3oDR0xm84STM8fRwKEfDgKo/8p+I6v2aqY+82Je4DFNVCQGvdqz2gcSeNvQhHYGJl7oVhYrRgDpAISD0d2ATE5Mm24kOA4FKxySgIWmUe+fLdxFWLij6I4gIvDnBw44kN6u1asnW8NCZi4+Ak6H/tgSbvutW+7++74EEG+RHhAQfyXSOXGczTYZnlt+YwJFadtJXM9kr1+xR7FPY0chePKdnmHw0QPvSiAarMllzOD4WDjeu1Oj1vSaOGNa7dT4h6dqF7V/slddLDDJAGdk1oeZcoOmX5+j7tl+7qdhKLE3YaGNiIfzkb0oQ2TbFCp4R3x6QPkIHh+fgVsA9yb907LSBtcTB4Q1ch/Y4BQV9s3eFuPQeBVuZZcNlLwOlmdh5slVnu8UVXIVet
    EDC_XAPIKEY: AgC8zyISMPRfeNIuBcNAAy6mC2e0VuvD/UMbhHmxk1z0bHZzGyyZDXZumGi2MYCuFlCG7Jsli2fAD8GRFCDArbqgmxkwTEKSEEsRbNXMy+IxfS9fpnzGlT2NhJOAxbuIbxvZIN2QDBD154YHsmC3scIHRKefwqxH7DhUMB1Wf1K7yvwa3Mbw7XqaHXuCBlMPVmIio5wOiVpbq2iBGD1jfXa1O1KPlRsJqMCHpp7D7VuuMJoLiP/SW+IY6wTU8ge2FcFMjluRo17FhEPvp7i1xmzblGm+oWPjlU7k+2404rsOEpi3Wx7YnowbNhmDmM3QtveKoQ7SEADu5xxZGkVeKmJ8g/4+vkw85oAr2vn7QxNDE4HhLusc6gVI2W90AUmdx7s5FUFVIkHu89r6UglaihlEPg8s/aW8e5qY++wdQU5Q61puCWWzLozda4/3dsuq78In7hThnHAHUttHltgh3H0hh4GHmXB82+YuTAeS1o+E6Y/75EdAnWx05LhcJ2H6hcMwISKTdyFtLqzN7St3zRjS56QvbAs6DGoY6NsOhJUZtu8qS/IbIwcnyd/UXo3nLhZDB9L36kEojGJGBJNn5Yd4DI/rxgxJxS1JavejPfjpZJCiABnzXnw7xDTBpBe7GMYsmjasiLUAUXM+JhnOySs4E4+5ceM+LHGjF/Af0XaGavBL69h7Hir8Qv72AvdJuRCdF7J/dtt+tw==
  template:
    metadata:
      creationTimestamp: null
      name: management-secrets
      namespace: edc-dev-provider-management
