#  Copyright 2024-2025 Dataport. All rights reserved. Developed as part of the POSSIBLE project.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

namespace: edc-dev
namePrefix: provider-
commonLabels:
  frontend: provider-portal


configMapGenerator:
  - name: participant-portal-config
    literals:
      - DAPSSERVER_URL_EXTERNAL=https://daps.int.possible-x.de/auth
      - DAPSSERVER_URL_INTERNAL=http://daps-daps-server:4567
      - DAPSSERVER_BASEURL=https://daps.dev.possible-x.de/auth
      - DIDWEBSERVICE_BASEURL=http://did-web-service:8080
      - DIDWEBSERVICE_IGNORESSL=false
      - FH_CATALOG_SPARQL_URL=https://catalog.dev.possible-x.de/ld/sparql/
      - FH_CATALOG_REPO_URL=https://hub.catalog.dev.possible-x.de/
      - FH_CATALOG_URIRESOURCEBASE=https://hub.catalog.dev.possible-x.de/resources/
      - SDCREATIONWIZARDAPI_BASEURL=https://sd-creation-wizard.dev.possible-x.de
      - SPRING_PROFILES_ACTIVE=dev
      - S3_BUCKETSTORAGEREGION=eu-central-3
      - PARTICIPANTID=did:web:didwebservice.dev.possible-x.de:participant:901e847f-bded-32d5-8301-c0e2dfa8439f
      # Specific Files
      - S3_BUCKETNAME=dev-provider-edc-bucket-possible-31952746
      - EDC_MGMTBASEURL=https://provider.edc.dev.possible-x.de/management
      - EDC_PROTOCOLBASEURL=https://provider.edc.dev.possible-x.de/protocol




images:
  - name: backend-image
    newName: ghcr.io/possible-x/backend
    newTag: a54b9ae9eb2dca28ba1c64d78587c4b728660100
  - name: frontend-image
    newName: ghcr.io/possible-x/frontend
    newTag: a54b9ae9eb2dca28ba1c64d78587c4b728660100

patches:
  - target:
      kind: Ingress
      name: participant-portal-ingress
    patch: |
      - op: replace
        path: /spec/tls/0/hosts/0
        value: management.provider.edc.dev.possible-x.de
      - op: replace
        path: /spec/tls/0/secretName
        value: management-provider-portal-ssl-certificate
      - op: replace
        path: /spec/rules/0/host
        value: management.provider.edc.dev.possible-x.de
      - op: replace
        path: /spec/rules/0/http/paths/0/backend/service/name
        value: provider-participant-portal-backend-svc
      - op: replace
        path: /spec/rules/0/http/paths/1/backend/service/name
        value: provider-participant-portal-frontend-svc
