spring:
  application:
    name: edc-orchestrator

management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: "/"
  endpoint:
    health:
      enabled: true

edc:
  x-api-key: 5678
  mgmt-base-url: http://localhost:19193/management

fh:
  catalog-url: https://possible.fokus.fraunhofer.de/api/hub/repo/catalogues/test-provider/datasets?valueType=identifiers