server:
  port: 8080

edc:
  x-api-key: password
  mgmt-base-url: http://localhost:19193/management
  protocol-base-url: http://localhost:19194/protocol

fh:
  catalog:
    url: https://possible.fokus.fraunhofer.de
    secret-key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsib3BlcmF0b3IiXX19.lMkYKTViVNVPFH49ntdkruLe5EaWRUYt1YL-1Y7b0gc

participant-id: "did:web:example-organization.eu"

s3:
  bucket-storage-region: "eu-central-3"
  bucket-top-level-folder: "possiblex_data_transfers"
  bucket-name: "dev-provider-edc-bucket-possible-31952746"