server:
  port: 8080

edc:
  x-api-key: password
  mgmt-base-url: http://localhost:19193/management
  protocol-base-url: http://localhost:19194/protocol

fh:
  catalog:
    url: url
    secret-key: secret

s3:
  bucket-storage-region: "eu-central-3"
  bucket-top-level-folder: "possiblex_data_transfers"
  bucket-name: "dev-provider-edc-bucket-possible-31952746"