server:
  port: 8080

edc:
  x-api-key: password
  mgmt-base-url: http://localhost:19193/management
  protocol-base-url: http://localhost:19194/protocol

participant-id: "did:web:didwebservice.dev.possible-x.de:participant:901e847f-bded-32d5-8301-c0e2dfa8439f"

s3:
  bucket-storage-region: "eu-central-3"
  bucket-top-level-folder: "possiblex_data_transfers"
  bucket-name: "dev-provider-edc-bucket-possible-31952746"

version.no: "1.0.0"