server:
  port: 8081

edc:
  x-api-key: password
  mgmt-base-url: http://localhost:29193/management
  protocol-base-url: http://localhost:29194/protocol

participant-id: "did:web:example-organization.eu"

s3:
  bucket-storage-region: "eu-central-3"
  bucket-top-level-folder: "possiblex_data_transfers"
  bucket-name: "dev-consumer-edc-bucket-possible-31952746"

version.no: "1.0.0"