spring:
  application:
    name: participant-portal

management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: "/"
  endpoint:
    health:
      enabled: true

edc:
  x-api-key: password
  mgmt-base-url: http://localhost:19193/management
  protocol-base-url: http://localhost:19194/protocol

springdoc:
  show-actuator: true

fh:
  catalog:
    url: url
    secret-key: secret
    catalog-name: test-provider

sd-creation-wizard-api:
  base-url: http://localhost:8085

participant-id: "did:web:example-organization.eu"

s3:
  bucket-storage: "s3-eu-central-2.ionoscloud.com"
  bucket-name: "dev-provider-edc-bucket-possible-31952746"
  bucket-target-path: "s3HatGeklappt/"
