spring:
  application:
    name: participant-portal
  security:
    admin:
      username: admin
      password: admin

management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: "/"
  endpoint:
    health:
      enabled: true

edc:
  x-api-key: password
  mgmt-base-url: http://localhost:19193/management
  protocol-base-url: http://localhost:19194/protocol

springdoc:
  show-actuator: true

fh:
  catalog:
    repo:
      url: url
    sparql:
      url: url
    secret-key: secret

sd-creation-wizard-api:
  base-url: http://localhost:8085

participant-id: "did:web:example-organization.eu"

daps-server:
  base-url: http://localhost:4567

s3:
  bucket-storage-region: "eu-central-3"
  bucket-top-level-folder: "possiblex_data_transfers"
  bucket-name: "dev-provider-edc-bucket-possible-31952746"

logging:
  level:
    reactor.netty.http.client: DEBUG

prefill-fields:
  data-product:
    json-file-path: "src/main/resources/prefillFieldsDataProduct.json"

version.no: "1.0.0"

version.date: "2024-12-31"