server:
  port: 8081

edc:
  x-api-key: password
  mgmt-base-url: http://localhost:29193/management

s3:
  bucket-storage: "s3-eu-central-2.ionoscloud.com"
  bucket-name: "dev-consumer-edc-bucket-possible-31952746"
  bucket-target-path: "s3HatGeklappt/"